### PR TITLE
fix(config): Make default values for executables user-visible

### LINKED ISSUE #88: getDefaultBazelExecutablePath() returns empty string
I have an empty setting for `bazel.executable` and the build task failed due to "build: command not found". After manually set `bazel.executable` to "bazel", build task works. I believe that `getDefaultBazelExecutablePath()` returns an empty string for some reason (though the code looks sane to me).

Please consider setting "bazel" as the default for `bazel.executable` or using [`WorkspaceConfiguration.get<T>(section: string, defaultValue: T)`](https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration) instead.

This is also the case for `bazel.buildifierExecutable`.

image

image

### PR DESCRIPTION
**Pull request by cbandera**
This change makes the default settings for the executable paths visible from the VSCode GUI and simplifies the code by moving the defaults to `package.json`.

Closes #88

### CODE REVIEW

**Comment by cameron-martin** [comment]
After this change if you set the settings to the empty string it fails to spawn bazel or buildifier. Since the empty string is never a valid executable, maybe we should keep the behaviour where we set a default value when the setting is the empty string?

File: src/buildifier/buildifier.ts [hunk 1]
```diff
@@ -118,33 +118,32 @@ export async function buildifierLint(
...
-  const bazelConfig = vscode.workspace.getConfiguration("bazel");
-  const buildifierExecutable = bazelConfig.get<string>("buildifierExecutable");
-  if (buildifierExecutable.length === 0) {
-    return "buildifier";
-  }
-  return buildifierExecutable;
+  return (
+    vscode.workspace
+      .getConfiguration("bazel")
+      .get<string>("buildifierExecutkable")
```
Comment (cameron-martin) [inline src/buildifier/buildifier.ts]: Looks like you've got a typo in this key. Possibly what's causing the test failures.

Comment (cameron-martin) [inline src/buildifier/buildifier.ts]:
```suggestion
      .get<string>("buildifierExecutable")
```
